import React from 'react';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Controller } from 'react-hook-form';
import { FormItem, FormLabel, FormControl, FormMessage, FormDescription } from '@/features/ui/components/form';
import { Input } from '@/features/ui/components/input';
import { Textarea } from '@/features/ui/components/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/features/ui/components/select';
/**
 * Sección de información básica del usuario
 */
export function BasicInfoSection (props: any){ control }) {
    return (_jsxs("div", { className: "space-y-6", children: [_jsx("h3", { className: "text-lg font-medium", children: "Informaci\u00F3n B\u00E1sica" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsx(Controller, { name: "displayName", control: control, render: ({ field }) => (_jsxs(FormItem, { children: [_jsx(FormLabel, { children: "Nombre completo" }), _jsx(FormControl, { children: _jsx(Input, { placeholder: "Tu nombre", ...field }) }), _jsx(FormMessage, {})] })) }), _jsx(Controller, { name: "username", control: control, render: ({ field }) => (_jsxs(FormItem, { children: [_jsx(FormLabel, { children: "Nombre de usuario" }), _jsx(FormControl, { children: _jsx(Input, { placeholder: "@usuario", ...field }) }), _jsx(FormMessage, {})] })) })] }), _jsx(Controller, { name: "bio", control: control, render: ({ field }) => (_jsxs(FormItem, { children: [_jsx(FormLabel, { children: "Biograf\u00EDa" }), _jsx(FormControl, { children: _jsx(Textarea, { placeholder: "Cu\u00E9ntanos sobre ti...", className: "min-h-[100px]", ...field }) }), _jsx(FormDescription, { children: "M\u00E1ximo 500 caracteres" }), _jsx(FormMessage, {})] })) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsx(Controller, { name: "role", control: control, render: ({ field }) => (_jsxs(FormItem, { children: [_jsx(FormLabel, { children: "Rol / Profesi\u00F3n" }), _jsxs(Select, { onValueChange: field.onChange, value: field.value, children: [_jsx(FormControl, { children: _jsx(SelectTrigger, { children: _jsx(SelectValue, { placeholder: "Selecciona un rol" }) }) }), _jsxs(SelectContent, { children: [_jsx(SelectItem, { value: "M\u00FAsico", children: "M\u00FAsico" }), _jsx(SelectItem, { value: "Artista visual", children: "Artista visual" }), _jsx(SelectItem, { value: "Fot\u00F3grafo", children: "Fot\u00F3grafo" }), _jsx(SelectItem, { value: "Otro", children: "Otro" })] })] }), _jsx(FormMessage, {})] })) }), _jsx(Controller, { name: "location", control: control, render: ({ field }) => (_jsxs(FormItem, { children: [_jsx(FormLabel, { children: "Ubicaci\u00F3n" }), _jsx(FormControl, { children: _jsx(Input, { placeholder: "Ciudad, Pa\u00EDs", ...field }) }), _jsx(FormMessage, {})] })) })] })] }));
}
